// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/internal/biz"
	"backend/internal/conf"
	"backend/internal/data"
	"backend/internal/server"
	"backend/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, casdoor *conf.Casdoor, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewCasdoor(casdoor)
	dataData, cleanup, err := data.NewData(confData, client, logger)
	if err != nil {
		return nil, nil, err
	}
	casdoorRepo := data.NewCasdoorRepo(dataData, logger)
	casdoorUsecase := biz.NewCasdoorUsecase(casdoorRepo, logger)
	casdoorService := service.NewCasdoorService(casdoorUsecase)
	httpServer := server.NewHTTPServer(confServer, casdoor, casdoorService)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
